In [265]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Вариант a:

$A*B$ = $4\times 2$ и $4\times 2$

$B*A$ = $4\times 2$ и $4\times 2$

Произведения не определены

Вариант б:

$A*B$ = $2\times 5$ и $5\times 3$, произведение определено, размерность полученной матрицы $2\times 3$

$B*A$ = $5\times 3$ и $2\times 5$, произведение не определено

Вариант в:

$A*B$ = $8\times 3$ и $3\times 8$, произведение определено, размерность полученной матрицы $8\times 8$

$B*A$ = $3\times 8$ и $8\times 3$, произведение определено, размерность полученной матрицы $3\times 3$

Вариант г:

$A*B$, $B*A$ - оба произведения определены, размерность полученной матрицы $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix}.$

In [266]:
a = np.array([[1,-2], [3,0]])
b = np.array([[4,-1], [0,5]])
result2_1 = a + b
result2_1

array([[ 5, -3],
       [ 3,  5]])

In [267]:
result2_2 = np.dot(a, b)
result2_2

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}.$

In [268]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])
result3 = (3 * a) + (-2 * b) + (4 * c)
result3

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [269]:
a = np.array([[4,1], [5,-2], [2,3]])
aT = a.T
aT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [270]:
result4_1 = np.dot(a, aT)
result4_1

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [271]:
result4_2 = np.dot(aT, a)
result4_2

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [272]:
def multiply_matrix(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        return ValueError('произведение не определено')
    result = [ [0 for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

Проверка работы

In [273]:
x = np.array([[1,-2], [3,0], [5,7]])
y = np.array([[4,-1], [0,5]])
print(f'Матрица Х:\n {x}')
print(f'Матрица Y:\n {y}')
print(f'Результат метода NumPy:\n {np.dot(x,y)}')
print(f'Результат собственного метода: \n {multiply_matrix(x,y)}')

Матрица Х:
 [[ 1 -2]
 [ 3  0]
 [ 5  7]]
Матрица Y:
 [[ 4 -1]
 [ 0  5]]
Результат метода NumPy:
 [[  4 -11]
 [ 12  -3]
 [ 20  30]]
Результат собственного метода: 
 [[4, -11], [12, -3], [20, 30]]
